---
# The Skylight ID for the application.
application: <%= ENV["SKYLIGHT_APPLICATION_ID"] %>

# The authentication token for the application.
authentication: <%= ENV["SKYLIGHT_AUTHENTICATION_TOKEN"] %>
